### PR TITLE
Update Pages “volunteer”

### PR DESCRIPTION
**Pull request by EvaRuthM**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by EvaRuthM** [comment]
Hey guys, I'm working on a blog post about our team needs and thought it would help to put our "stack" on the volunteer page. Would love your input – hope I did this right! 
Thanks.

**Review by LayaTaal — APPROVED** [review]
This looks good to me. I think it might be more readable if you make the stack a list of items instead of a long paragraph.

**Comment by EvaRuthM** [comment]
> This looks good to me. I think it might be more readable if you make the stack a list of items instead of a long paragraph.

Thanks Jason! Just changed it to a bulleted list. Let me know if you like that better.

**Review by judan — APPROVED** [review]
LGTM 👍🏽

**Pull request merged**
